AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:

  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
    
  HelloFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.hello
      Runtime: nodejs12.x
      CodeUri: ./hello
      Policies:
        - Statement:
          - Sid: EventBridgePutEvents 
            Effect: "Allow"
            Action: 
              - "events:PutEvents"
            Resource: "*"
      Events:
        HelloAPI:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /hello
            Method: GET

  ByeFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.bye
      Runtime: nodejs12.x
      CodeUri: ./bye      
  
  ByeFunctionInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref ByeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt MyEventsRule.Arn

  MyEventsRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: "Say Bye"
      EventPattern: { "source": ["say.bye"] }
      Targets:
        - Arn: !GetAtt ByeFunction.Arn
          Id: "RuleId"

Outputs:
  Region:
    Description: "Region"
    Value: !Ref AWS::Region

  ApiId:
    Description: "API ID"
    Value: !Ref MyApi

  ApiUrl:
    Description: "API endpoint URL for Prod environment"
    Value: !Sub 'https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/dev/'